### ISSUE TITLE
Not able to extract the densenet.pt.tar file

### ISSUE THREAD

**Issue by Allhailankurgupta** [ShaohuiLin/GAL#3]
Hello ShaohuiLin could you please help me I was not able to extract the densenet.pt.tar file
it gives this error
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by colorjam** [comment]
Hi, @Allhailankurgupta . The pre-trained model does not need to be uncompressed. You can use it as following: 
```
checkpoint = torch.load('densenet.pt.tar')
state_dict = checkpoint['state_dict']
model.load_state_dict(state_dict)
```
More details can be found: https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-and-loading-models

**Comment by Allhailankurgupta** [comment]
Thanks
